services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: digno
      POSTGRES_USER: digno
      POSTGRES_PASSWORD: digno123
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build: ./backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DEBUG=1
      - DATABASE_URL=postgresql://digno:digno123@db:5432/digno

  frontend:
    build: ./frontend
    command: sh -c "HOST=0.0.0.0 PORT=3000 npm run dev"
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - next_build_cache:/app/.next
    ports:
      - "3000:3000"
    environment:
      - DOCKER=true

volumes:
  postgres_data:
  next_build_cache: