# Railway configuration
[build]
  builder = "dockerfile"
  dockerfilePath = "Dockerfile"

[deploy]
  startCommand = "python manage.py migrate && python manage.py collectstatic --noinput && gunicorn digno.wsgi:application --bind 0.0.0.0:$PORT"

[env]
  DJANGO_SETTINGS_MODULE = "digno.settings"