# Generated by Django 4.2.24 on 2025-09-22 16:47

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Donation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("first_name", models.CharField(blank=True, max_length=100)),
                ("last_name", models.CharField(blank=True, max_length=100)),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("1.00"))
                        ],
                    ),
                ),
                ("is_recurring", models.BooleanField(default=False)),
                ("stripe_customer_id", models.CharField(blank=True, max_length=100)),
                (
                    "stripe_subscription_id",
                    models.CharField(blank=True, max_length=100),
                ),
                (
                    "stripe_payment_intent_id",
                    models.CharField(blank=True, max_length=100),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("completed_date", models.DateTimeField(blank=True, null=True)),
                ("message", models.TextField(blank=True, max_length=500)),
            ],
            options={
                "ordering": ["-created_date"],
            },
        ),
    ]
