# Generated by Django 4.2.24 on 2025-09-22 16:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("donations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="donation",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="donations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="donation",
            index=models.Index(
                fields=["user", "-created_date"], name="donations_d_user_id_e0ec21_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="donation",
            index=models.Index(
                fields=["status", "-created_date"], name="donations_d_status_081575_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="donation",
            index=models.Index(
                fields=["is_recurring", "-created_date"],
                name="donations_d_is_recu_fa2b30_idx",
            ),
        ),
    ]
