# Generated by Django 4.2.24 on 2025-09-22 16:47

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(blank=True, max_length=200, unique=True)),
                ("content", ckeditor_uploader.fields.RichTextUploadingField()),
                (
                    "summary",
                    models.TextField(
                        help_text="Brief summary of the article", max_length=300
                    ),
                ),
                (
                    "featured_image",
                    models.ImageField(blank=True, null=True, upload_to="articles/"),
                ),
                ("is_published", models.BooleanField(default=False)),
                ("published_date", models.DateTimeField(blank=True, null=True)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                (
                    "tags",
                    models.CharField(
                        blank=True, help_text="Comma-separated tags", max_length=200
                    ),
                ),
                ("meta_description", models.CharField(blank=True, max_length=160)),
                ("view_count", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["-published_date", "-created_date"],
            },
        ),
    ]
