# Generated by Django 4.2.24 on 2025-09-22 17:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("articles", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="co_author",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional co-author for collaborative articles",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="co_authored_articles",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
