# Generated by Django 4.2.24 on 2025-09-22 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0003_article_co_author"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="category",
            field=models.CharField(
                choices=[
                    ("BREAKING_NEWS", "Breaking News"),
                    ("ECONOMY", "Economy"),
                    ("POLITICS", "Politics"),
                    ("FOREIGN_AFFAIRS", "Foreign Affairs"),
                    ("IMMIGRATION", "Immigration"),
                    ("HUMAN_RIGHTS", "Human Rights"),
                    ("LEGISLATION", "Legislation"),
                    ("OPINION", "Opinion"),
                ],
                default="POLITICS",
                help_text="Primary category for this article",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="is_breaking_news",
            field=models.BooleanField(
                default=False, help_text="Mark as breaking news regardless of category"
            ),
        ),
    ]
