# Generated by Django 4.2.24 on 2025-09-24 15:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('articles', '0004_article_category_article_is_breaking_news'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='featured_image',
            field=models.ImageField(blank=True, help_text='Direct image upload', null=True, upload_to='articles/'),
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Upload image file', upload_to='images/%Y/%m/')),
                ('title', models.CharField(help_text='Internal title for organizing images', max_length=200)),
                ('description', models.TextField(help_text='Caption/description that appears with the image', max_length=500)),
                ('alt_text', models.CharField(help_text='Alt text for accessibility', max_length=255)),
                ('source', models.CharField(help_text="Photo credit/source (e.g., 'Laura Buckman/AFP via Getty Images')", max_length=200)),
                ('source_url', models.URLField(blank=True, help_text='Optional link to original source')),
                ('width', models.PositiveIntegerField(blank=True, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('file_size', models.PositiveIntegerField(blank=True, help_text='File size in bytes', null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('usage_count', models.PositiveIntegerField(default=0, help_text='Number of times this image has been used')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_images', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
        migrations.AddField(
            model_name='article',
            name='featured_image_asset',
            field=models.ForeignKey(blank=True, help_text='Use image from media library', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='featured_in_articles', to='articles.image'),
        ),
        migrations.AddIndex(
            model_name='image',
            index=models.Index(fields=['-created_date'], name='articles_im_created_563466_idx'),
        ),
        migrations.AddIndex(
            model_name='image',
            index=models.Index(fields=['uploaded_by', '-created_date'], name='articles_im_uploade_c45c80_idx'),
        ),
    ]
