# Generated by Django 4.2.24 on 2025-09-25 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_alter_article_featured_image_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='scheduled_publish_time',
            field=models.DateTimeField(blank=True, help_text='If set, article will be published at this time.', null=True),
        ),
    ]
