# Generated by Django 4.2.24 on 2025-10-06 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_remove_article_tags_tag_article_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='subtitle',
            field=models.CharField(blank=True, help_text='Optional subtitle for the article', max_length=300),
        ),
    ]
