# Generated by Django 4.2.24 on 2025-10-07 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_article_subtitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='last_published_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
