# Generated by Django 4.2.24 on 2025-09-24 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_subscriber',
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('subscriber', 'Subscriber'), ('writer', 'Writer'), ('editor', 'Editor')], default='subscriber', help_text='User role: subscriber, writer, or editor', max_length=20),
        ),
    ]
